start:
  print "NebukinPrompt - Nebukin Petr Operating System - NebukinBasic DEMO #1"
  print "1-0-1 MODEL"
  print "-"
  print Starting in 3 seconds...
  pause 30
  print "1"
  sound 500 5
  print "0"
  pause 50
  print "1"
  sound 500 5
  pause 10
  print "1"
  sound 500 5
  print "0"
  pause 50
  print "1"
  sound 500 5
  pause 10
  print "1"
  sound 500 5
  print "0"
  pause 50
  print "1"
  sound 500 5
  pause 10
end